name: reddays
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
# This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_auth_web: ^5.13.4
  firebase_core_web: ^2.18.1
  firebase_database: ^11.0.0 

  url_launcher: ^6.1.9 # Replace with the latest version
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting recommendations for good coding practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets for your project
  assets:
    - assets/images/skull.png
    - assets/data/leaderboard.json

  # Custom fonts (uncomment if you need to use fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
